CC=gcc
CFLAGS=-c -Wall -O3
MOVE=mv *.o obj/
HDRS=src/headers/
SRC=src/source/
OBJ=obj/

main.o:	$(SRC)main.c
	$(CC) $(CFLAGS) $(SRC)main.c && $(MOVE)
	
usuario.o:	$(HDRS)usuario.h	$(SRC)usuario.c
	$(CC) $(CFLAGS) $(SRC)usuario.c && $(MOVE)

sharius:        $(OBJ)usuario.o $(OBJ)main.o
	$(CC) $(OBJ)usuario.o $(OBJ)main.o -o sharius

run:
	./sharius

clean:
	rm -rf $(OBJ)*
